Repository josemanuel286/Proyecto-Hotel-Bellastar, pull requests merged in 2022-03, with the labels that each got.

#22 Se cambió el título
  index.html
Labels: enhancement

#38 Se agrego la opción número de personas
  booking.html
Labels: bug

#43 delete fetch
  admin/carnivalBD.html
Labels: documentation
